DROP TABLE IF EXISTS users,
vehicles;

CREATE TABLE IF NOT EXISTS users (
  ID SERIAL PRIMARY KEY,
  Username VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS vehicles (
  ID SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  lat VARCHAR(255),
  long VARCHAR(255),
  image_URL VARCHAR(255),
  CL_URL VARCHAR(255),
  user_ID INT,
  FOREIGN KEY (user_ID) REFERENCES users(ID)
);