DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS
users (
  ID SERIAL PRIMARY KEY,
  Username VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS vehicles;

CREATE TABLE IF NOT EXISTS
vehicles (
  ID SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  lat VARCHAR(2083),
  lng VARCHAR(2083),
  image_URL VARCHAR(2083),
  CL_URL VARCHAR(2083)
);